version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: RDI_Container
    volumes:
      - .:/RDI
    image: app:RDI
    ports:
      - "8000:8000"
