# Generated by Django 4.2.4 on 2023-08-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_rotateimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RotateImage',
        ),
    ]
